In [1]:
import pandas as pd
import torch
import torch.nn as nn


In [2]:
data=pd.read_csv("/content/Student_Performance (1).csv")

In [3]:
data.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0


In [4]:
input = torch.tensor(data['Previous Scores'].values, dtype = torch.float32).reshape(-1,1)
output = torch.tensor(data['Performance Index'].values, dtype = torch.float32).reshape(-1,1)


In [5]:
model = nn.Sequential(
    nn.Linear(1, 8),
    nn.ReLU(),
    nn.Linear(8, 1)
)


In [6]:
error = nn.MSELoss()

In [7]:
optim = torch.optim.SGD(model.parameters(), lr = 0.001)

In [8]:
for i in range(1000):
  pred = model(input)
  loss = error(pred , output)

  optim.zero_grad()
  loss.backward()
  optim.step()

  if i % 100 == 0:
    print(f"epoch {i}, loss = {loss.item():.4f}")

epoch 0, loss = 4255.9355
epoch 100, loss = 2790.8816
epoch 200, loss = 1991.8136
epoch 300, loss = 1456.3972
epoch 400, loss = 1097.6409
epoch 500, loss = 857.2551
epoch 600, loss = 696.1840
epoch 700, loss = 588.2580
epoch 800, loss = 515.9426
epoch 900, loss = 467.4873


In [9]:
print(model(torch.tensor([[3.0]])))

tensor([[47.1048]], grad_fn=<AddmmBackward0>)


In [16]:
for name, param in model.named_parameters():
    print(name, param)

0.weight Parameter containing:
tensor([[-1.8562e+03],
        [-1.5232e+03],
        [-1.8507e+00],
        [-4.1255e-03],
        [-7.3477e-01],
        [-2.3143e+00],
        [-7.7745e-01],
        [-7.0346e-01]], requires_grad=True)
0.bias Parameter containing:
tensor([-25.3645, -21.2693,   0.1690,  -0.1177,  -0.2592,  -0.2018,   0.4708,
          0.1692], requires_grad=True)
2.weight Parameter containing:
tensor([[-1.1656e+03, -1.1316e+03,  3.3135e+00, -2.6613e-01, -2.5995e-01,
          8.0548e+00,  3.1877e-01, -1.1704e-01]], requires_grad=True)
2.bias Parameter containing:
tensor([47.1048], requires_grad=True)
