In [ ]:
import pandas as pd
import torch
import torch.nn as nn

data = pd.read_csv("/content/Student_Performance.csv")
print(data)

      Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0                 7               99                        Yes            9   
1                 4               82                         No            4   
2                 8               51                        Yes            7   
3                 5               52                        Yes            5   
4                 7               75                         No            8   
...             ...              ...                        ...          ...   
9995              1               49                        Yes            4   
9996              7               64                        Yes            8   
9997              6               83                        Yes            8   
9998              9               97                        Yes            7   
9999              7               74                         No            8   

      Sample Question Papers Practiced 

In [ ]:
input = torch.tensor(data['Sleep Hours'].values,dtype=torch.float32).reshape(-1,1)
output =torch.tensor(data['Hours Studied'].values,dtype = torch.float32).reshape(-1,1)

model = nn.Linear(1,1)
error = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(),lr=0.001)

In [ ]:
for i in range(1000):
  pred = model(input)
  loss = error(pred,output)

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

In [ ]:
print(model(torch.tensor([[3.0]])))

tensor([[2.0939]], grad_fn=<AddmmBackward0>)


In [ ]:
model.weight

Parameter containing:
tensor([[0.7320]], requires_grad=True)

In [ ]:
model.bias

Parameter containing:
tensor([-0.1021], requires_grad=True)

In [ ]:
model_path = "./student_performance_model.pth"
torch.save(model.state_dict(), model_path)
print(f"Model saved to {model_path}")

Model saved to ./student_performance_model.pth
